Projeto.Beta/UI.Web/Areas/Painel/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UI.Web.Areas.Painel.Controllers
{
    public class AdminController : Controller
    {
        //
        // GET: /Painel/Admin/

        public ActionResult Index()
        {
            return View();
        }

    }
}

Projeto.Beta/UI.Web/Areas/Painel/Controllers/AdministrativoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UI.Web.Areas.Painel.Controllers
{
    public class AdministrativoController : Controller
    {
        //
        // GET: /Painel/Administrativo/

        public ActionResult Index()
        {
            return View();
        }

    }
}

Projeto.Beta/UI.Web/Areas/Painel/Controllers/PainelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UI.Web.Areas.Painel.Controllers
{
    public class PainelController : Controller
    {
        //
        // GET: /Painel/Painel/

        public ActionResult Index()
        {
            return View();
        }

    }
}

Projeto.Beta/UI.Web/Areas/Painel/Controllers/UsuarioApiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using Aplicacao;
using Dominio;

namespace UI.Web.Areas.Painel.Controllers
{
    public class UsuarioApiController : ApiController
    {
        private UsuarioAplicacao usuarioAplicacao;

        public ICollection<Usuario> Get(string filtro = "", string busca = "")
        {
            usuarioAplicacao = new UsuarioAplicacao();

            if (string.IsNullOrEmpty(busca))
                return usuarioAplicacao.ListarUsuario();
            switch (filtro.ToLower())
            {
                case "nome":
                    return usuarioAplicacao.ListarUsuarioPorNome(busca);
                case "login":
                    return usuarioAplicacao.ListarUsuarioPorLogin(busca);
                default:
                    return usuarioAplicacao.ListarUsuario();
            }
        }

        [HttpPost]
        public ObjetoRetorno<Usuario> Post(Usuario usuario)
        {
            usuarioAplicacao = new UsuarioAplicacao();
            return usuarioAplicacao.Salvar(usuario);
        }
    }
}

Projeto.Beta/UI.Web/Areas/Painel/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UI.Web.Areas.Painel.Controllers
{
    public class UsuarioController : Controller
    {
        //
        // GET: /Painel/Usuario/

        public ActionResult Index()
        {
            return View();
        }

    }
}

Projeto.Beta/UI.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UI.Web.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            return View();
        }

    }
}

Projeto.Beta/UI.Web/Areas/Painel/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Projeto Beta - Painel de Controle";
}

<div class="hero-unit">
    <h1>Projeto Beta</h1>
    <p>Este projeto visa demonstrar o uso das tecnologias MongoDb, Knokcou JS, Twitter Bootstrap e ASP .Net Web API</p>
    <p><a href="javascript:;" class="btn btn-primary btn-large">Para saber mais &raquo;</a></p>
</div>

<div class="row">
    <div class="span6">
        <h2>MongoDb</h2>
        <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
        <p><a href="javascript:;" class="btn">Veja mais</a></p>
    </div>
    <div class="span6">
        <h2>Knockout JS</h2>
        <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
        <p><a href="javascript:;" class="btn">Veja mais</a></p>
    </div>
</div>
<div class="row">
    <div class="span6">
        <h2>Twitter Bootstrap</h2>
        <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
        <p><a href="javascript:;" class="btn">Veja mais</a></p>
    </div>
    <div class="span6">
        <h2>ASP.Net Web API</h2>
        <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
        <p><a href="javascript:;" class="btn">Veja mais</a></p>
    </div>
</div>

Projeto.Beta/UI.Web/Areas/Painel/Views/Administrativo/Index.cshtml
@{
    ViewBag.Title = "Projeto Beta - Administrativo";
}

<div class="row-fluid">
    @Html.Partial("_MenuAdministrativo")
    <div class="span9">
        <div class="span12" style="margin-left: 10px">
            <div class="row">
                <div class="span12">
                    <div class="page-header">
                        <h1>Administrativo <small>aqui você pode administrar</small></h1>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="span6">
                    <h2>Usuário</h2>
                    <p>Nesta seção você pode administrar os usuário do sistema, setando as permissões do mesmo.</p>
                    <p><a href="javascript:;" class="btn">Acessar &raquo;</a></p>
                </div>
                <div class="span6">
                    <h2>Grupo de Usuários</h2>
                    <p>Nesta seção você cri os grupos dos usuários, organizando assim os usuários do sistema.</p>
                    <p><a href="javascript:;" class="btn">Acessar &raquo;</a></p>
                </div>
            </div>
        </div>
    </div>
</div>

Projeto.Beta/UI.Web/Areas/Painel/Views/Painel/Index.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>Projeto Beta - Painel</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
</head>
    <body>
        <div class="container">
            <div class="row">
                <div class="page-header">
                    <h1>Projeto Beta <small>MongoDb, Twitter Bootstrap, KnockoutJS e ASP.Net</small></h1>
                </div>
            </div>
            <div class="row">
                <div class="span4">
                    <p></p>
                </div>
                <div class="span4">
                    <form action="" method="POST" class="form-horizontal">
                        <legend>Acessar o sistema</legend>
                        <label for="nome">Usuário:</label>
                        <input type="text" name="nome" class="span4"/>
                        
                        <label for="senha">Senha:</label>
                        <input type="password" name="senha" class="span4"/>
                        <div class="span4"><p></p></div>
                        <button type="submit" class="btn btn-primary pull-right">Entrar</button>
                    </form>
                </div>
                <div class="span4">
                    <p></p>
                </div>
            </div>
        </div>

        <script src="~/Scripts/bootstrap.js"></script>
    </body>
</html>

Projeto.Beta/UI.Web/Areas/Painel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/knockoutformulario")
    
   
    
    <script src="~/Scripts/bootstrap-typeahead.js"></script>
    <script src="~/Scripts/bootstrap-alert.js"></script>
    <script src="~/Scripts/bootstrap-button.js"></script>
    <script src="~/Scripts/bootstrap-carousel.js"></script>
    <script src="~/Scripts/bootstrap-collapse.js"></script>
    <script src="~/Scripts/bootstrap-dropdown.js"></script>
    <script src="~/Scripts/bootstrap-modal.js"></script>
    
    <script src="~/Scripts/bootstrap-scrollspy.js"></script>
    <script src="~/Scripts/bootstrap-tab.js"></script>
    <script src="~/Scripts/bootstrap-tooltip.js"></script>
    <script src="~/Scripts/bootstrap-transition.js"></script>
    <style type="text/css">
        body {
            padding-top: 75px;
            padding-bottom: 40px;
        }
    </style>
</head>
<body>

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <a class="brand" href="javascript:;">Projeto Beta</a>

                <div class="btn-group pull-right">
                    <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="icon-user"></i>Cleyton Ferrari
                            <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="javascript:;">Perfil</a></li>
                        <li class="divider"></li>
                        <li><a href="javascript:;">Sair</a></li>
                    </ul>
                </div>
                <div class="nav-collapse collapse">
                    <ul class="nav">
                        <li class="active"><a href="javascript:;">Home</a></li>
                        <li><a href="javascript:;">Administrativo</a></li>
                        <li><a href="javascript:;">Cadastro</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        @RenderBody()

        <hr />
        <footer>
            <p>&copy; Projeto Beta 2012</p>
        </footer>
    </div>

    
    @RenderSection("scripts", required: false)
</body>
</html>

Projeto.Beta/UI.Web/Areas/Painel/Views/Shared/_MenuAdministrativo.cshtml
<div class="span3">
    <div class="well">
        <ul class="nav nav-list">
            <li class="nav-header">Administrativo</li>
            <li><a href="javascript:;">Usuário</a></li>
            <li><a href="javascript:;">Grupo de Usuário</a></li>
        </ul>
    </div>
</div>

Projeto.Beta/UI.Web/Areas/Painel/Views/Usuario/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<script src="~/Scripts/app/painel/UsuarioViewModel.js"></script>

<div class="row-fluid">
    @Html.Partial("_MenuAdministrativo")
    <div class="span9">
        <div class="span12" style="margin-left: 15px">
            <form>
                <div class="span12">
                    <div class="span3">
                        <select class="span12" data-bind="options: filtros, optionsText: 'chave', optionsValue:'valor', value: filtroSelecionado">
                            
                        </select>
                    </div>
                    <div class="span9 input-append">
                        <input class="span9" id="appendedInputButtons" type="text" data-bind="value: busca">
                        <button class="btn" type="button" data-bind="click: buscar">Buscar</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="span12">
            
            
            <div class="alert" data-bind="visible: informacaoDaTransacao().mensagens.length > 0, css: {'alert-error': informacaoDaTransacao().erro, 'alert-success': informacaoDaTransacao().sucesso, 'alert-info': informacaoDaTransacao().alerta }">
                <ul data-bind="foreach: informacaoDaTransacao().mensagens">
                    <li data-bind="text: $data"></li>
                </ul>
            </div>
            <!-- ko if: listaDeResultados().length > 0 -->
            <table class="table table-condensed table-striped table-hover">
                <thead>
                    <tr>
                        <th>Nome</th>
                        <th>Login</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <!-- ko foreach: listaDeResultados() -->
                    <tr>
                        <td class="span6" data-bind="text: objeto.Nome"></td>
                        <td class="span4" data-bind="text: objeto.Login"></td>
                        <td class="span2"><a href="javascript:;" data-bind="click: $root.preencheFormComResultadoDaBusca.bind($data, objeto)">Selecionar</a></td>
                    </tr>
                    <!-- /ko -->
                </tbody>
            </table>
            <!-- /ko -->
        </div>
        <div class="span12">
            <form>
                <legend>Cadastro de grupo de usuários</legend>
                <div class="span12">
                    <div class="span7">
                        <label for="">Nome de usuário</label>
                        <input class="span12" type="text" data-bind="value: nome" placeholder="Digite o nome completo do usuário">
                    </div>
                    <div class="span5">
                        <label for="">Login</label>
                        <input class="span12" type="text" data-bind="value: login" placeholder="Login para acessar o sistema">
                    </div>
                </div>
                <div class="span12">
                    <div class="span5">
                        <label for="">Senha</label>
                        <input class="span12" type="password" data-bind="value: senha">
                    </div>
                    <div class="span5">
                        <label for="">Confirmar Senha</label>
                        <input class="span12" type="password" data-bind="value: confirmarSenha">
                    </div>
                </div>
                <div class="span12">
                    <button type="submit" data-bind="click: salvar" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </div>

</div>

Projeto.Beta/UI.Web/Views/Home/Index.cshtml
@Html.ActionLink("Acessar o Painel","Index","Painel")

Projeto.Beta/UI.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>